#!/usr/bin/env python3
"""
Convert the raw product photo folders into web-ready WebP images.

    python3 scripts/build-images.py [path/to/photo/folders]

Source folders default to the parent of this repo. Originals are never modified.
Writes:
  assets/products/<slug>/<colour>-<n>.webp      (1200px, product page)
  assets/products/<slug>/<colour>-<n>-sm.webp   (560px, cards & thumbnails)
  data/images.js                                (manifest used by the site)

To add a product: drop its folder next to the others, add an entry to
FOLDERS below, add it to data/products.js, and re-run.
"""
import json
import os
import re
import sys

from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else os.path.dirname(ROOT)
OUT = os.path.join(ROOT, "assets", "products")

# folder name -> (slug, {filename prefix: colour key})
# Folders of Gemini_Generated_* files have no prefix; list files per colour
# explicitly with "files", or leave empty to treat everything as one colour.
FOLDERS = {
    "198 Double top": ("double-top-set", {"m": "mustard", "o": "rose", "p": "teal"}),
    "3100": ("hello-baby-set", {}),
    "3413 night suit": ("printed-night-suit", {"o": "peach", "p": "pink"}),
    "6644": ("checked-hooded-jumpsuit", {"gold": "mustard", "pink": "pink", "pista": "pistachio"}),
    "FS 44846": ("little-star-cardigan-set", {"b": "blue", "r": "red"}),
    "KING": ("sleeveless-button-romper", {"g": "green", "o": "orange", "y": "yellow"}),
    "MIXMIX 1531": ("striped-dungaree-set", {}),
    "T G 2653": ("hooded-teddy-suit", {"f": "cream", "p": "pistachio", "pink": "pink"}),
    "T G 799 ONION": ("zip-fleece-suit", {}),
    "TG 5649": ("tiger-stripe-suit", {"b": "black", "o": "orange", "r": "red"}),
    "TG 6445": ("zip-bomber-jogger-set", {"a": "sage", "b": "olive", "c": "slate", "d": "brown", "e": "plum", "f": "beige"}),
    "TeWE": ("collar-sleepsuit", {"c": "beige", "l": "ivory"}),
    "cut sleeve DT": ("sleeveless-vest-set", {"b": "navy", "r": "red", "y": "yellow"}),
    "teensy": ("newborn-cap-bib-set", {"b": "aqua", "c": "cream", "o": "peach"}),
    "top and bottom set": ("star-cloud-jogger-set", {
        "files": {
            "rust": ["axnxty", "fo13x3", "frr70e", "jqlgad", "tpyan3"],
            "blue": ["buckfk", "fj8bj6", "o0oxco", "p47mgz", "p7ow5a"],
        }
    }),
}

SIZES = {"": 1200, "-sm": 560}
EXTS = (".png", ".jpg", ".jpeg", ".webp")


def group(folder, mapping):
    files = sorted(f for f in os.listdir(folder) if f.lower().endswith(EXTS))
    groups = {}
    if "files" in mapping:
        for colour, keys in mapping["files"].items():
            groups[colour] = [f for k in keys for f in files if k in f]
        return groups
    if not mapping:
        return {"default": files}
    for f in files:
        m = re.match(r"([a-zA-Z]+)(\d+)", f)
        if not m or m.group(1) not in mapping:
            print(f"  ! skipping unmapped file {f}")
            continue
        groups.setdefault(mapping[m.group(1)], []).append((int(m.group(2)), f))
    return {c: [f for _, f in sorted(v)] for c, v in groups.items()}


def main():
    manifest = {}
    for name, (slug, mapping) in FOLDERS.items():
        folder = os.path.join(SRC, name)
        if not os.path.isdir(folder):
            print(f"! missing folder: {folder}")
            continue
        dest = os.path.join(OUT, slug)
        os.makedirs(dest, exist_ok=True)
        manifest[slug] = {}
        for colour, files in group(folder, mapping).items():
            paths = []
            for i, f in enumerate(files, 1):
                base = f"{colour}-{i}"
                src_path = os.path.join(folder, f)
                for suffix, px in SIZES.items():
                    out = os.path.join(dest, f"{base}{suffix}.webp")
                    if os.path.exists(out) and os.path.getmtime(out) >= os.path.getmtime(src_path):
                        continue
                    im = ImageOps.exif_transpose(Image.open(src_path)).convert("RGB")
                    im.thumbnail((px, px), Image.LANCZOS)
                    im.save(out, "WEBP", quality=78 if suffix == "" else 72, method=6)
                paths.append(f"assets/products/{slug}/{base}")
            manifest[slug][colour] = paths
        print(f"{slug}: " + ", ".join(f"{c}×{len(p)}" for c, p in manifest[slug].items()))

    with open(os.path.join(ROOT, "data", "images.js"), "w") as fh:
        fh.write("// Generated by scripts/build-images.py — do not edit by hand.\n")
        fh.write("window.PRODUCT_IMAGES = " + json.dumps(manifest, indent=2) + ";\n")


if __name__ == "__main__":
    main()
